### ISSUE TITLE
REPL cannot print Date object

### ISSUE THREAD

**Issue by sergeysova** [effector/repl#15]
**What is the current behavior:**

```js
console.log(new Date())
// => {}
```

**Please provide the steps to reproduce and if possible a minimal demo of the problem via https://share.effector.dev, https://codesandbox.io or similar**

https://share.effector.dev/sfNkGl1Q

**What is the expected behavior:**

It is should print the date

Related effector/effector#620

**Comment by zerobias** [comment]
Related module with console parser implementation: https://github.com/effector/repl/blob/main/src/features/logs/lib/console/react-inspector/fork/ObjectInspector.tsx

**Comment by sergeysova** [comment]
Implemented in https://github.com/effector/repl/commit/442ee63a9dc07cae55f0a481deb801bd072672bb

![image](https://user-images.githubusercontent.com/5620073/152678557-8bd78951-afd2-498b-8c9c-53dab2d13059.png)
